import React from 'react';
import { Meta, StoryObj } from '@storybook/react';
import { TextStyleCatalog, TextStyle } from './TextStyleCatalog';

const styles: Record<string, TextStyle> = {
  'M3/mobile/display/large': {
    fontFamily: 'LibreFranklin',
    fontSize: '57px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.12',
    letterSpacing: '-0.25px',
  },
  'M3/mobile/display/medium': {
    fontFamily: 'LibreFranklin',
    fontSize: '45px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.16',
    letterSpacing: 'normal',
  },
  'M3/mobile/display/small': {
    fontFamily: 'LibreFranklin',
    fontSize: '36px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.22',
    letterSpacing: 'normal',
  },
  'M3/mobile/headline/large': {
    fontFamily: 'LibreFranklin',
    fontSize: '32px',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.25',
    letterSpacing: 'normal',
  },
  'M3/mobile/headline/medium': {
    fontFamily: 'LibreFranklin',
    fontSize: '28px',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.29',
    letterSpacing: 'normal',
  },
  'M3/web/IBM-Plex-Mono/h1': {
    fontFamily: 'IBMPlexMono',
    fontSize: '28px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/web/Libre-Franklin/h1': {
    fontFamily: 'LibreFranklin',
    fontSize: '28px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/web/IBM-Plex-Mono/h2': {
    fontFamily: 'IBMPlexMono',
    fontSize: '25px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/web/Libre-Franklin/h2': {
    fontFamily: 'LibreFranklin',
    fontSize: '25px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/mobile/headline/small': {
    fontFamily: 'LibreFranklin',
    fontSize: '24px',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.33',
    letterSpacing: 'normal',
  },
  'M3/web/IBM-Plex-Mono/h3': {
    fontFamily: 'IBMPlexMono',
    fontSize: '22px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/web/Libre-Franklin/h3': {
    fontFamily: 'LibreFranklin',
    fontSize: '22px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/mobile/title/large': {
    fontFamily: 'LibreFranklin',
    fontSize: '22px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.27',
    letterSpacing: 'normal',
  },
  'M3/web/IBM-Plex-Mono/h4': {
    fontFamily: 'IBMPlexMono',
    fontSize: '20px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/web/Libre-Franklin/h4': {
    fontFamily: 'LibreFranklin',
    fontSize: '20px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/web/IBM-Plex-Mono/body': {
    fontFamily: 'IBMPlexMono',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/mobile/label/large - prominent': {
    fontFamily: 'IBMPlexMono',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.25',
    letterSpacing: '0.1px',
  },
  'M3/web/Libre-Franklin/body': {
    fontFamily: 'LibreFranklin',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/mobile/title/medium': {
    fontFamily: 'LibreFranklin',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.5',
    letterSpacing: '0.15px',
  },
  'M3/mobile/body/large': {
    fontFamily: 'LibreFranklin',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.5',
    letterSpacing: '0.5px',
  },
  'M3/web/IBM-Plex-Mono/caption': {
    fontFamily: 'IBMPlexMono',
    fontSize: '14px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/mobile/label/large': {
    fontFamily: 'IBMPlexMono',
    fontSize: '14px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.43',
    letterSpacing: '0.1px',
  },
  'M3/web/Libre-Franklin/caption': {
    fontFamily: 'LibreFranklin',
    fontSize: '14px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/mobile/title/small': {
    fontFamily: 'LibreFranklin',
    fontSize: '14px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.43',
    letterSpacing: '0.1px',
  },
  'M3/mobile/body/medium': {
    fontFamily: 'LibreFranklin',
    fontSize: '14px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.43',
    letterSpacing: '0.25px',
  },
  'M3/web/IBM-Plex-Mono/small': {
    fontFamily: 'IBMPlexMono',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/mobile/label/medium - prominent': {
    fontFamily: 'IBMPlexMono',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.33',
    letterSpacing: '0.5px',
  },
  'M3/mobile/label/medium': {
    fontFamily: 'IBMPlexMono',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.33',
    letterSpacing: '0.5px',
  },
  'M3/web/Libre-Franklin/small': {
    fontFamily: 'LibreFranklin',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
  },
  'M3/mobile/body/small': {
    fontFamily: 'LibreFranklin',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.33',
    letterSpacing: '0.4px',
  },
  'M3/mobile/label/small': {
    fontFamily: 'IBMPlexMono',
    fontSize: '8px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '2',
    letterSpacing: '0.5px',
  },
};

export default {
  title: 'Design System/Typography',
  component: TextStyleCatalog,
  parameters: {
    backgrounds: {
      default: 'dark',
      values: [
        { name: 'dark', value: '#1b2d3e' },
      ],
    },
  },
} as Meta<typeof TextStyleCatalog>;

type Story = StoryObj<typeof TextStyleCatalog>;

export const Default: Story = {
  args: {
    styles: styles,
  },
};
